services:
  - type: web
    name: fishh-backend
    env: node
    rootDir: backend
    repo: https://github.com/tanayamhatre7/Live-Fish-E-commerce-Platform
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
